In [42]:
import pandas as pd

In [43]:
df = pd.read_csv("./data.csv")

In [44]:
df

,Unnamed: 0,aiddata_id,aiddata_2_id,year,donor,recipient,commitment_amount_usd_constant,coalesced_purpose_code,coalesced_purpose_name
0,1,2.414478e+06,NaN,1977,Saudi Arabia,India,348718518.0,23030,Power generation/renewable sources
1,2,2.414509e+06,NaN,1977,Saudi Arabia,Brazil,191647004.0,23040,Electrical transmission/ distribution
2,3,2.414635e+06,NaN,1983,Saudi Arabia,India,79371799.0,21030,Rail transport
3,4,2.414665e+06,NaN,1984,Saudi Arabia,Taiwan,212202942.0,21030,Rail transport
4,5,2.414667e+06,NaN,1984,Saudi Arabia,Korea,134511154.0,21040,Water transport
5,6,2.414684e+06,NaN,1985,Saudi Arabia,India,128074768.0,23000,"Energy generation and supply, combinations of ..."
6,7,2.414760e+06,NaN,1987,Saudi Arabia,India,72707674.0,21040,Water transport
7,8,2.414840e+06,NaN,1993,Kuwait,Cyprus,25461230.0,21020,Road transport
8,9,2.415076e+06,NaN,1996,Kuwait,Lithuania,21381183.0,23050,Gas distribution
9,10,2.415206e+06,NaN,1998,Kuwait,India,1107033.0,21020,Road transport
10,11,2.426999e+06,NaN,1978,Kuwait,India,103885863.0,23000,"Energy generation and supply, combinations of ..."
11,12,2.427052e+06,NaN,1976,Kuwait,India,193588873.0,23030,Power generation/renewable sources
12,13,2.427058e+06,NaN,1976,Kuwait,Thailand,12905925.0,23040,Electrical transmission/ distribution
13,14,2.427115e+06,NaN,2001,Kuwait,Slovak Republic,1219994.0,14020,Water supply and sanitation - large systems
14,15,2.428296e+06,NaN,1992,Kuwait,Cyprus,6635123.0,21020,Road transport
15,16,2.428502e+06,NaN,1989,Kuwait,India,43493083.0,31320,Fishery development
16,17,2.428506e+06,NaN,1988,Kuwait,Cyprus,16145060.0,21020,Road transport
17,18,2.428566e+06,NaN,1988,Kuwait,Cyprus,27769503.0,14020,Water supply and sanitation - large systems
18,19,2.428587e+06,NaN,1986,Kuwait,Cyprus,30606432.0,21020,Road transport
19,20,2.428601e+06,NaN,1986,Kuwait,India,53561256.0,23030,Power generation/renewable sources
20,21,2.428623e+06,NaN,1984,Kuwait,Cyprus,27051193.0,14040,River development
21,22,2.428652e+06,NaN,1983,Kuwait,India,133092433.0,32220,Mineral/Metal prospection and exploration
22,23,2.428882e+06,NaN,1982,Kuwait,India,131175647.0,32120,Industrial development
23,24,2.428885e+06,NaN,1982,Kuwait,Thailand,50452172.0,23030,Power generation/renewable sources
24,25,2.428888e+06,NaN,1983,Kuwait,Cyprus,21878208.0,21020,Road transport
25,26,2.428969e+06,NaN,1981,Kuwait,India,83971160.0,43010,Multisector aid
26,27,2.428974e+06,NaN,1981,Kuwait,Thailand,65310902.0,23020,Power generation/non-renewable sources
27,28,2.429003e+06,NaN,1981,Kuwait,India,149282062.0,23020,Power generation/non-renewable sources
28,29,2.429034e+06,NaN,1979,Kuwait,Thailand,59307807.0,23000,"Energy generation and supply, combinations of ..."
29,30,2.429037e+06,NaN,1980,Kuwait,Cyprus,23153412.0,14040,River development
...,...,...,...,...,...,...,...,...,...
98510,98511,9.060009e+11,NaN,2013,Portugal,Chile,109.0,16061,Culture and recreation
98511,98512,9.060009e+11,NaN,2013,Poland,Brazil,63571.0,11420,Higher education
98512,98513,9.060009e+11,NaN,2013,Greece,India,24288.0,11420,Higher education
98513,98514,9.060009e+11,NaN,2013,Poland,Brazil,1657.0,11420,Higher education
98514,98515,9.060009e+11,NaN,2013,Poland,Brazil,4141.0,11420,Higher education
98515,98516,9.060009e+11,NaN,2013,Greece,Brazil,25253.0,11420,Higher education
98516,98517,9.060009e+11,NaN,2013,Portugal,Brazil,17651.0,24020,Monetary institutions
98517,98518,9.060009e+11,NaN,2013,Slovak Republic,Chile,2296.0,11420,Higher education
98518,98519,9.060009e+11,NaN,2013,Greece,Chile,1671.0,11420,Higher education
98519,98520,9.060009e+11,NaN,2013,Portugal,Brazil,197649.0,43082,Research/scientific institutions
98520,98521,9.060009e+11,NaN,2013,New Zealand,India,7911.0,11420,Higher education
98521,98522,9.060009e+11,NaN,2013,New Zealand,Brazil,81580.0,24030,Formal sector financial intermediaries
98522,98523,9.060009e+11,NaN,2013,New Zealand,Brazil,52072.0,11420,Higher education
98523,98524,9.060009e+11,NaN,2013,New Zealand,Chile,73769.0,15110,Economic and development policy/planning
98524,98525,9.060009e+11,NaN,2013,New Zealand,South Africa,112232.0,91010,Administrative costs
98525,98526,9.060009e+11,NaN,2013,New Zealand,India,954657.0,16030,Housing policy and administrative management
98526,98527,9.060009e+11,NaN,2013,New Zealand,Chile,245607.0,11420,Higher education
98527,98528,9.060009e+11,NaN,2013,New Zealand,Colombia,244739.0,31100,"Agriculture, combinations of purposes in Agric..."
98528,98529,9.060009e+11,NaN,2013,New Zealand,South Africa,27772.0,11420,Higher education
98529,98530,9.060009e+11,NaN,2013,New Zealand,South Africa,77240.0,15110,Economic and development policy/planning
98530,98531,9.060009e+11,NaN,2013,New Zealand,Thailand,60751.0,11320,Secondary education
98531,98532,9.060009e+11,NaN,2013,Czech Republic,Brazil,4001.0,11320,Secondary education
98532,98533,9.060009e+11,NaN,2013,Czech Republic,Thailand,127.0,15110,Economic and development policy/planning
98533,98534,9.060009e+11,NaN,2013,Czech Republic,Chile,3678.0,15110,Economic and development policy/planning
98534,98535,9.060009e+11,NaN,2013,Czech Republic,South Africa,2382.0,11105,"Education, level unspecified, purpose unspecif..."
98535,98536,9.060009e+11,NaN,2013,Czech Republic,Colombia,51840.0,11420,Higher education
98536,98537,9.060009e+11,NaN,2013,Czech Republic,India,35380.0,72010,Material relief assistance and services
98537,98538,9.060009e+11,NaN,2013,Czech Republic,India,11930.0,11420,Higher education
98538,98539,9.060009e+11,NaN,2013,Czech Republic,Brazil,6669.0,16010,Social/ welfare services
98539,98540,9.060009e+11,NaN,2013,Czech Republic,Chile,7145.0,11120,Education facilities and training

In [45]:
data_agg = df.groupby(['coalesced_purpose_code'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [46]:
data_agg.nlargest(5, 'commitment_amount_usd_constant')

     coalesced_purpose_code  commitment_amount_usd_constant
92                    21050                    3.981348e+10
90                    21030                    2.078091e+10
170                   32120                    1.974833e+10
230                   60040                    1.795495e+10
105                   23020                    1.634623e+10

In [47]:
purpose_list = [21050,21030,32120,60040,23020]

In [48]:
data_r = df[["recipient","donor","coalesced_purpose_code","commitment_amount_usd_constant"]]

In [106]:
data_r_ = df[["recipient","donor","coalesced_purpose_code","coalesced_purpose_name","commitment_amount_usd_constant"]]

In [107]:
data_r_ = data_r_[data_r_['coalesced_purpose_code'] == 21030]

In [108]:
data_r_

,recipient,donor,coalesced_purpose_code,coalesced_purpose_name,commitment_amount_usd_constant
2,India,Saudi Arabia,21030,Rail transport,7.937180e+07
3,Taiwan,Saudi Arabia,21030,Rail transport,2.122029e+08
153,Australia,United States,21030,Rail transport,6.837255e+07
168,India,United States,21030,Rail transport,3.140579e+07
264,Brazil,United States,21030,Rail transport,2.177698e+07
280,Brazil,United States,21030,Rail transport,9.874004e+07
329,Brazil,United States,21030,Rail transport,3.624109e+07
773,Korea,United States,21030,Rail transport,1.325493e+06
835,India,United States,21030,Rail transport,1.870893e+06
841,India,United States,21030,Rail transport,8.350610e+05
854,India,United States,21030,Rail transport,1.123312e+06
986,Brazil,United States,21030,Rail transport,3.660970e+07
987,Brazil,United States,21030,Rail transport,1.145323e+08
1230,Korea,United States,21030,Rail transport,1.042075e+08
7310,Brazil,Japan,21030,Rail transport,1.228517e+06
7327,Brazil,Japan,21030,Rail transport,1.265000e+03
7405,Chile,Japan,21030,Rail transport,6.591000e+03
7484,Colombia,Japan,21030,Rail transport,2.635100e+04
7576,India,Japan,21030,Rail transport,1.121935e+06
7577,India,Japan,21030,Rail transport,6.680700e+04
7623,India,Japan,21030,Rail transport,9.160448e+08
7624,India,Japan,21030,Rail transport,1.831393e+07
7630,India,Japan,21030,Rail transport,3.131633e+07
7646,India,Japan,21030,Rail transport,6.022810e+05
7760,Thailand,Japan,21030,Rail transport,6.144400e+04
7836,Thailand,Japan,21030,Rail transport,7.271855e+08
7837,Thailand,Japan,21030,Rail transport,3.010262e+07
8261,Thailand,Korea,21030,Rail transport,1.119080e+05
8767,Thailand,Germany,21030,Rail transport,5.883224e+06
9138,India,Japan,21030,Rail transport,6.771533e+08
...,...,...,...,...,...
75697,India,Japan,21030,Rail transport,6.835632e+08
75698,India,Japan,21030,Rail transport,5.165480e+07
75699,India,Japan,21030,Rail transport,1.078400e+09
75700,India,Japan,21030,Rail transport,3.039096e+07
75701,India,Japan,21030,Rail transport,2.801889e+08
75702,India,Japan,21030,Rail transport,7.284494e+06
76374,Thailand,Japan,21030,Rail transport,2.043958e+08
77195,Brazil,United States,21030,Rail transport,2.042620e+05
77206,Chile,United States,21030,Rail transport,1.021300e+04
79119,Brazil,Canada,21030,Rail transport,1.769300e+04
79624,Brazil,Japan,21030,Rail transport,1.909900e+04
79828,India,Japan,21030,Rail transport,7.446040e+07
79836,India,Japan,21030,Rail transport,1.743515e+08
79846,India,Japan,21030,Rail transport,4.138210e+05
79951,Thailand,Japan,21030,Rail transport,1.464850e+05
79952,Thailand,Japan,21030,Rail transport,2.712340e+05
80343,Colombia,France,21030,Rail transport,1.870977e+08
85996,India,France,21030,Rail transport,8.216490e+05
91824,India,Japan,21030,Rail transport,1.597599e+09
91825,India,Japan,21030,Rail transport,2.155633e+07
93988,India,United States,21030,Rail transport,7.244900e+04
94315,Brazil,United States,21030,Rail transport,4.402380e+05
94640,India,France,21030,Rail transport,1.423534e+08
96042,India,Japan,21030,Rail transport,3.046332e+07
96043,India,Japan,21030,Rail transport,1.084679e+07
96061,India,Japan,21030,Rail transport,5.574227e+07
96071,India,Japan,21030,Rail transport,1.091462e+09
96073,India,Japan,21030,Rail transport,3.904761e+08
96074,India,Japan,21030,Rail transport,5.294568e+08
96883,Colombia,Korea,21030,Rail transport,5.885400e+04

In [49]:
data_r = data_r[data_r['coalesced_purpose_code'].isin([purpose for purpose in purpose_list])]

In [50]:
data_r

,recipient,donor,coalesced_purpose_code,commitment_amount_usd_constant
2,India,Saudi Arabia,21030,7.937180e+07
3,Taiwan,Saudi Arabia,21030,2.122029e+08
22,India,Kuwait,32120,1.311756e+08
26,Thailand,Kuwait,23020,6.531090e+07
27,India,Kuwait,23020,1.492821e+08
90,Australia,United States,21050,9.545075e+07
91,Sweden,United States,32120,1.913961e+07
92,Chile,United States,32120,5.494769e+07
96,India,United States,21050,3.274508e+08
98,Colombia,United States,23020,9.091619e+06
99,Australia,United States,21050,1.907982e+06
100,Australia,United States,21050,6.914680e+05
101,Australia,United States,21050,1.935537e+08
102,Australia,United States,21050,3.940371e+07
103,Australia,United States,21050,8.328704e+07
104,Australia,United States,21050,1.464081e+08
105,Australia,United States,21050,8.906814e+07
106,Australia,United States,21050,2.309162e+07
107,Australia,United States,21050,6.949634e+07
113,Czech Republic,United States,23020,6.013932e+07
114,Czech Republic,United States,23020,5.122991e+07
115,Czech Republic,United States,21050,8.391294e+07
116,Czech Republic,United States,32120,2.357778e+07
117,Czech Republic,United States,21050,1.816480e+08
118,Denmark,United States,21050,9.733314e+06
120,Denmark,United States,21050,1.146632e+07
121,Denmark,United States,21050,6.202169e+07
126,Australia,United States,21050,6.025467e+06
127,Australia,United States,21050,4.337055e+08
128,Australia,United States,21050,7.499275e+07
...,...,...,...,...
94442,Brazil,United States,21050,1.074995e+06
94450,Brazil,United States,23020,2.885030e+05
94640,India,France,21030,1.423534e+08
95096,Brazil,Spain,21050,9.160000e+02
95098,Brazil,Spain,21050,3.931900e+04
96042,India,Japan,21030,3.046332e+07
96043,India,Japan,21030,1.084679e+07
96061,India,Japan,21030,5.574227e+07
96071,India,Japan,21030,1.091462e+09
96073,India,Japan,21030,3.904761e+08
96074,India,Japan,21030,5.294568e+08
96671,Brazil,Japan,32120,6.394200e+04
96687,Thailand,Korea,23020,7.694000e+03
96689,Thailand,Korea,21050,6.612000e+03
96704,Brazil,Korea,32120,1.232070e+05
96708,Colombia,Korea,32120,3.442290e+05
96883,Colombia,Korea,21030,5.885400e+04
96998,Colombia,Germany,32120,1.682090e+05
97404,India,Germany,23020,7.227729e+07
97405,India,Germany,23020,1.248426e+08
97561,South Africa,Germany,32120,4.490920e+05
97600,South Africa,Germany,32120,7.476100e+04
97658,South Africa,Germany,32120,1.904940e+05
97666,India,Germany,32120,5.405700e+04
97674,South Africa,Germany,32120,1.378960e+05
97804,India,Norway,32120,2.148900e+05
97806,India,Norway,32120,6.430000e+03
97958,India,Norway,32120,7.248400e+04
98140,Brazil,Italy,23020,1.567700e+04
98411,South Africa,Netherlands,32120,8.364900e+04

In [51]:
data_r1 = data_r.groupby(['recipient'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [52]:
top_10r = data_r1.nlargest(10, 'commitment_amount_usd_constant')

In [53]:
a = list(top_10r['recipient'])

In [54]:
a

['India',
 'Poland',
 'Thailand',
 'Korea',
 'Brazil',
 'Canada',
 'Saudi Arabia',
 'Colombia',
 'Australia',
 'Taiwan']

In [55]:
data_r2 = data_r.groupby(['donor'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [56]:
top_20d = data_r2.nlargest(20, 'commitment_amount_usd_constant')

In [57]:
b = list(top_20d['donor'])

In [58]:
b

['United States',
 'Japan',
 'Germany',
 'France',
 'United Kingdom',
 'Belgium',
 'Italy',
 'Saudi Arabia',
 'Canada',
 'Kuwait',
 'Norway',
 'Denmark',
 'Netherlands',
 'Finland',
 'Austria',
 'Switzerland',
 'Sweden',
 'Australia',
 'Spain',
 'Korea']

In [59]:
data_r = data_r[data_r['recipient'].isin([recipient for recipient in a])]

In [60]:
data_r = data_r[data_r.donor.isin(b)]

In [61]:
data_r

,recipient,donor,coalesced_purpose_code,commitment_amount_usd_constant
2,India,Saudi Arabia,21030,7.937180e+07
3,Taiwan,Saudi Arabia,21030,2.122029e+08
22,India,Kuwait,32120,1.311756e+08
26,Thailand,Kuwait,23020,6.531090e+07
27,India,Kuwait,23020,1.492821e+08
90,Australia,United States,21050,9.545075e+07
96,India,United States,21050,3.274508e+08
98,Colombia,United States,23020,9.091619e+06
99,Australia,United States,21050,1.907982e+06
100,Australia,United States,21050,6.914680e+05
101,Australia,United States,21050,1.935537e+08
102,Australia,United States,21050,3.940371e+07
103,Australia,United States,21050,8.328704e+07
104,Australia,United States,21050,1.464081e+08
105,Australia,United States,21050,8.906814e+07
106,Australia,United States,21050,2.309162e+07
107,Australia,United States,21050,6.949634e+07
126,Australia,United States,21050,6.025467e+06
127,Australia,United States,21050,4.337055e+08
128,Australia,United States,21050,7.499275e+07
129,Australia,United States,21050,3.573153e+07
132,India,United States,32120,1.687755e+07
133,India,United States,32120,1.364150e+05
135,India,United States,23020,4.867479e+07
137,India,United States,21050,5.653431e+06
138,India,United States,32120,2.953902e+07
141,India,United States,32120,1.511753e+06
142,India,United States,32120,1.214408e+07
147,India,United States,21050,8.887681e+08
149,Australia,United States,21050,1.191375e+08
...,...,...,...,...
94328,India,United States,21050,7.293820e+05
94346,Brazil,United States,21050,6.713900e+04
94354,Brazil,United States,21050,7.230000e+03
94381,Brazil,United States,21050,9.223400e+05
94441,Brazil,United States,21050,7.250130e+05
94442,Brazil,United States,21050,1.074995e+06
94450,Brazil,United States,23020,2.885030e+05
94640,India,France,21030,1.423534e+08
95096,Brazil,Spain,21050,9.160000e+02
95098,Brazil,Spain,21050,3.931900e+04
96042,India,Japan,21030,3.046332e+07
96043,India,Japan,21030,1.084679e+07
96061,India,Japan,21030,5.574227e+07
96071,India,Japan,21030,1.091462e+09
96073,India,Japan,21030,3.904761e+08
96074,India,Japan,21030,5.294568e+08
96671,Brazil,Japan,32120,6.394200e+04
96687,Thailand,Korea,23020,7.694000e+03
96689,Thailand,Korea,21050,6.612000e+03
96704,Brazil,Korea,32120,1.232070e+05
96708,Colombia,Korea,32120,3.442290e+05
96883,Colombia,Korea,21030,5.885400e+04
96998,Colombia,Germany,32120,1.682090e+05
97404,India,Germany,23020,7.227729e+07
97405,India,Germany,23020,1.248426e+08
97666,India,Germany,32120,5.405700e+04
97804,India,Norway,32120,2.148900e+05
97806,India,Norway,32120,6.430000e+03
97958,India,Norway,32120,7.248400e+04
98140,Brazil,Italy,23020,1.567700e+04

In [62]:
data_r = data_r.groupby(['recipient','donor','coalesced_purpose_code'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [63]:
data_r

,recipient,donor,coalesced_purpose_code,commitment_amount_usd_constant
0,Australia,United States,21030,6.837255e+07
1,Australia,United States,21050,2.414954e+09
2,Australia,United States,32120,8.970500e+06
3,Brazil,Austria,32120,5.167098e+06
4,Brazil,Belgium,32120,1.152172e+06
5,Brazil,Belgium,60040,9.530131e+07
6,Brazil,Canada,21030,1.769300e+04
7,Brazil,Canada,23020,6.054352e+06
8,Brazil,Canada,32120,2.974866e+07
9,Brazil,France,21030,1.112452e+08
10,Brazil,France,23020,5.386837e+07
11,Brazil,France,60040,3.917663e+07
12,Brazil,Germany,21030,3.974931e+07
13,Brazil,Germany,23020,3.504114e+07
14,Brazil,Germany,32120,8.235516e+07
15,Brazil,Germany,60040,3.838057e+08
16,Brazil,Italy,23020,1.567700e+04
17,Brazil,Italy,32120,7.806570e+05
18,Brazil,Japan,21030,1.249130e+06
19,Brazil,Japan,21050,1.001650e+05
20,Brazil,Japan,32120,3.019423e+08
21,Brazil,Japan,60040,1.160096e+08
22,Brazil,Korea,32120,1.232070e+05
23,Brazil,Norway,32120,8.083100e+04
24,Brazil,Spain,21030,1.403750e+05
25,Brazil,Spain,21050,1.406770e+05
26,Brazil,Spain,32120,1.110417e+06
27,Brazil,Switzerland,32120,1.034972e+06
28,Brazil,United Kingdom,23020,9.881680e+07
29,Brazil,United Kingdom,32120,3.917481e+07
...,...,...,...,...
186,Thailand,France,21050,6.384930e+05
187,Thailand,France,23020,1.473564e+08
188,Thailand,France,32120,2.398183e+07
189,Thailand,Germany,21030,1.623912e+08
190,Thailand,Germany,23020,5.431390e+07
191,Thailand,Germany,32120,1.663684e+08
192,Thailand,Germany,60040,5.898800e+05
193,Thailand,Italy,21030,1.488852e+06
194,Thailand,Japan,21030,5.249206e+09
195,Thailand,Japan,21050,2.648320e+09
196,Thailand,Japan,23020,2.236434e+07
197,Thailand,Japan,32120,1.348022e+09
198,Thailand,Korea,21030,1.119080e+05
199,Thailand,Korea,21050,5.233500e+04
200,Thailand,Korea,23020,1.094230e+05
201,Thailand,Korea,32120,1.096198e+06
202,Thailand,Kuwait,23020,6.531090e+07
203,Thailand,Netherlands,32120,1.381313e+07
204,Thailand,Norway,21050,6.050200e+04
205,Thailand,Norway,32120,6.304303e+06
206,Thailand,Saudi Arabia,23020,9.567654e+07
207,Thailand,Spain,32120,3.243500e+04
208,Thailand,Sweden,32120,1.325932e+07
209,Thailand,Switzerland,23020,6.063103e+06
210,Thailand,United Kingdom,21030,1.287469e+07
211,Thailand,United Kingdom,32120,1.231750e+08
212,Thailand,United States,21030,1.874200e+04
213,Thailand,United States,21050,1.378790e+09
214,Thailand,United States,23020,6.196218e+08
215,Thailand,United States,32120,1.460262e+09

In [64]:
d = data_r[data_r['coalesced_purpose_code'] == 21030]

In [65]:
d

,recipient,donor,coalesced_purpose_code,commitment_amount_usd_constant
0,Australia,United States,21030,6.837255e+07
6,Brazil,Canada,21030,1.769300e+04
9,Brazil,France,21030,1.112452e+08
12,Brazil,Germany,21030,3.974931e+07
18,Brazil,Japan,21030,1.249130e+06
24,Brazil,Spain,21030,1.403750e+05
31,Brazil,United States,21030,3.095600e+08
37,Colombia,Austria,21030,2.814444e+06
42,Colombia,France,21030,1.870977e+08
45,Colombia,Germany,21030,1.915580e+08
52,Colombia,Japan,21030,2.635100e+04
55,Colombia,Korea,21030,5.885400e+04
63,Colombia,United States,21030,1.543880e+05
67,India,Australia,21030,2.671116e+06
76,India,Canada,21030,1.594100e+05
83,India,France,21030,1.657800e+08
88,India,Germany,21030,2.849852e+08
95,India,Japan,21030,1.151979e+10
101,India,Netherlands,21030,4.206527e+07
109,India,Saudi Arabia,21030,7.937180e+07
110,India,Spain,21030,1.949700e+04
113,India,Sweden,21030,4.306879e+06
117,India,United Kingdom,21030,2.149151e+08
122,India,United States,21030,3.599736e+07
127,Korea,France,21030,2.209200e+04
129,Korea,Germany,21030,2.901501e+07
131,Korea,Japan,21030,9.030520e+08
133,Korea,United States,21030,1.055330e+08
142,Poland,France,21030,1.262932e+06
146,Poland,Italy,21030,1.342614e+06
148,Poland,Japan,21030,2.569417e+06
149,Poland,Sweden,21030,3.830000e+02
152,Poland,United Kingdom,21030,4.116330e+05
155,Poland,United States,21030,3.263300e+04
161,Saudi Arabia,United States,21030,3.865530e+05
167,Taiwan,Saudi Arabia,21030,2.122029e+08
170,Thailand,Australia,21030,3.636709e+07
175,Thailand,Belgium,21030,4.307740e+05
181,Thailand,Denmark,21030,5.010773e+06
185,Thailand,France,21030,1.092113e+08
189,Thailand,Germany,21030,1.623912e+08
193,Thailand,Italy,21030,1.488852e+06
194,Thailand,Japan,21030,5.249206e+09
198,Thailand,Korea,21030,1.119080e+05
210,Thailand,United Kingdom,21030,1.287469e+07
212,Thailand,United States,21030,1.874200e+04

In [66]:
for purpose in purpose_list:
    data_r[data_r['coalesced_purpose_code'] == purpose].to_csv("./"+str(purpose)+".csv")

In [67]:
data_r = data_r.groupby(['recipient','donor'], as_index=False).agg({"commitment_amount_usd_constant": "sum"})

In [68]:
data_r

       recipient           donor  commitment_amount_usd_constant
0      Australia   United States                    2.492297e+09
1         Brazil         Austria                    5.167098e+06
2         Brazil         Belgium                    9.645348e+07
3         Brazil          Canada                    3.582070e+07
4         Brazil          France                    2.042902e+08
5         Brazil         Germany                    5.409513e+08
6         Brazil           Italy                    7.963340e+05
7         Brazil           Japan                    4.193012e+08
8         Brazil           Korea                    1.232070e+05
9         Brazil          Norway                    8.083100e+04
10        Brazil           Spain                    1.391469e+06
11        Brazil     Switzerland                    1.034972e+06
12        Brazil  United Kingdom                    1.445289e+08
13        Brazil   United States                    6.550037e+09
14        Canada   United States                    4.068597e+09
15      Colombia         Austria                    2.814444e+06
16      Colombia         Belgium                    9.086740e+05
17      Colombia          Canada                    2.324521e+07
18      Colombia         Denmark                    2.004500e+05
19      Colombia          France                    2.185427e+08
20      Colombia         Germany                    2.935903e+08
21      Colombia           Italy                    5.178147e+07
22      Colombia           Japan                    1.876640e+05
23      Colombia           Korea                    4.030830e+05
24      Colombia     Netherlands                    2.025344e+06
25      Colombia           Spain                    3.800741e+06
26      Colombia     Switzerland                    7.431490e+05
27      Colombia  United Kingdom                    1.131226e+07
28      Colombia   United States                    2.541050e+09
29         India       Australia                    3.102313e+07
..           ...             ...                             ...
59        Poland          Sweden                    8.395190e+05
60        Poland  United Kingdom                    4.590176e+07
61        Poland   United States                    1.364049e+09
62  Saudi Arabia         Austria                    2.036620e+05
63  Saudi Arabia           Japan                    2.222245e+08
64  Saudi Arabia   United States                    3.803858e+09
65        Taiwan          France                    7.083000e+04
66        Taiwan           Japan                    1.201758e+06
67        Taiwan    Saudi Arabia                    2.122029e+08
68        Taiwan   United States                    2.248054e+09
69      Thailand       Australia                    3.673991e+07
70      Thailand         Austria                    2.281844e+06
71      Thailand         Belgium                    4.321272e+06
72      Thailand          Canada                    9.686821e+07
73      Thailand         Denmark                    1.293894e+07
74      Thailand         Finland                    5.811118e+07
75      Thailand          France                    2.811880e+08
76      Thailand         Germany                    3.836633e+08
77      Thailand           Italy                    1.488852e+06
78      Thailand           Japan                    9.267912e+09
79      Thailand           Korea                    1.369864e+06
80      Thailand          Kuwait                    6.531090e+07
81      Thailand     Netherlands                    1.381313e+07
82      Thailand          Norway                    6.364805e+06
83      Thailand    Saudi Arabia                    9.567654e+07
84      Thailand           Spain                    3.243500e+04
85      Thailand          Sweden                    1.325932e+07
86      Thailand     Switzerland                    6.063103e+06
87      Thailand  United Kingdom                    1.360497e+08
88      Thailand   United States                    3.458693e+09

[89 rows x 3 columns]

In [69]:
donor = data_r['donor'].unique()

In [70]:
donor

array(['United States', 'Austria', 'Belgium', 'Canada', 'France',
       'Germany', 'Italy', 'Japan', 'Korea', 'Norway', 'Spain',
       'Switzerland', 'United Kingdom', 'Denmark', 'Netherlands',
       'Australia', 'Finland', 'Kuwait', 'Saudi Arabia', 'Sweden'], dtype=object)

In [71]:
recipient = data_r['recipient'].unique()

In [72]:
list_ = list(donor) + list(recipient)

In [73]:
my_set = set(list_)
my_new_list = list(my_set)

In [74]:
my_new_list

['Kuwait',
 'Spain',
 'Australia',
 'Japan',
 'Canada',
 'Switzerland',
 'France',
 'Thailand',
 'Brazil',
 'Finland',
 'United Kingdom',
 'Saudi Arabia',
 'Belgium',
 'Denmark',
 'Netherlands',
 'Korea',
 'Sweden',
 'Austria',
 'Norway',
 'United States',
 'Italy',
 'Colombia',
 'Taiwan',
 'Germany',
 'India',
 'Poland']

In [75]:
import numpy as np
np.savetxt("countries.csv", my_new_list , delimiter=",", fmt='%s', header="countries")